#ifndef ABSTRACTION_MEMORY_VIRTUAL_CONVERTER_H
#define ABSTRACTION_MEMORY_VIRTUAL_CONVERTER_H

#ifdef X86
#include "x86/memory/definitions.h"
#else
#error ABSTRACTION_MEMORY_VIRTUAL_CONVERTER_H
#endif

#endif
